name: Auth0 Tenant Change

on:
  pull_request:
    branches: [main]
  push:
    branch: [change]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
      AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
      AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.0.0"
      - run: npm ci
      - run: npm run import
